"""add generated questions table

Revision ID: db0d40dd5932
Revises: e0fcf505ff94
Create Date: 2026-07-22 02:07:00.433923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'db0d40dd5932'
down_revision: Union[str, Sequence[str], None] = 'e0fcf505ff94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_sets')
    op.drop_table('student_attempts')
    op.drop_table('questions')
    op.drop_table('learning_preferences')
    op.drop_table('student_answers')
    op.alter_column('generated_questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('generated_questions', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_table('student_answers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('attempt_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('selected_answer', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['student_attempts.id'], name=op.f('student_answers_attempt_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('student_answers_question_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_answers_pkey'))
    )
    op.create_table('learning_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teaching_style', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('learning_mode', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('learning_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('learning_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('learning_preferences_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_set_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_text', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_a', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_b', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_c', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('option_d', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('correct_answer', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('explanation', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], name=op.f('questions_question_set_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('questions_pkey'))
    )
    op.create_table('student_attempts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('question_set_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('correct_answers', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('total_questions', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['question_set_id'], ['question_sets.id'], name=op.f('student_attempts_question_set_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('student_attempts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('student_attempts_pkey'))
    )
    op.create_table('question_sets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('lesson_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('generated_by_model', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('question_sets_pkey'))
    )
    # ### end Alembic commands ###
